// One-off: organizes the ORIGINAL 132 catalog sheets (public/catalogs/*.pdf,
// already generated by scripts/generateCatalogPdfs.mjs) into a folder tree
// that mirrors the website's real category taxonomy (src/app/products/
// categoryTaxonomy.ts), so the owner/team can browse "Interior Paints >
// Emulsions > ..." etc. exactly like the site's Products mega-menu, instead
// of one flat folder of 132 files.
//
// Deliberately does NOT touch the 38 corrected-sheet PDFs the client is
// merging in separately (see scripts/updateCatalogPdfs38.mjs, not run here)
// — this only reads the already-generated public/catalogs/<slug>.pdf files
// and copies them into the category tree under their real product name.
//
// Parses data.ts / categoryTaxonomy.ts as text rather than importing them
// (plain Node can't import .ts modules without a loader), so this stays a
// zero-dependency script like the others in this folder.

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const CATALOG_DIR = path.join(ROOT, "public", "catalogs");
const OUT_DIR = "C:/Users/Pranav/Downloads/Colorsome_Catalog_By_Category";

// ── Parse products (name, slug, category) out of data.ts ───────────────────
const dataTs = fs.readFileSync(path.join(ROOT, "src/app/products/data.ts"), "utf8");
const dataLines = dataTs.split("\n");
const startIdx = dataLines.findIndex((l) => l.startsWith("export const products"));
const products = [];
for (let i = startIdx + 1; i < dataLines.length; i++) {
  const line = dataLines[i];
  if (!/^\s*\{\s*id:\s*"\d+"/.test(line)) continue;
  const nameM = line.match(/name:\s*"([^"]+)"/);
  const slugM = line.match(/slug:\s*"([^"]+)"/);
  const catM = line.match(/category:\s*"([^"]+)"/);
  if (nameM && slugM && catM) {
    products.push({ name: nameM[1], slug: slugM[1], category: catM[1] });
  }
}

// ── Parse the taxonomy out of categoryTaxonomy.ts ───────────────────────────
const taxTs = fs.readFileSync(path.join(ROOT, "src/app/products/categoryTaxonomy.ts"), "utf8");
const columnBlocks = taxTs.split(/\{\s*\n\s*slug:\s*"/).slice(1);
const CATEGORY_LOOKUP = {}; // raw category string -> { top, sub }
for (const block of columnBlocks) {
  const titleM = block.match(/title:\s*"([^"]+)"/);
  if (!titleM) continue;
  const top = titleM[1];
  // subcategory sub-blocks within this column, up to the next top-level column
  const subRe = /label:\s*"([^"]+)",\s*categories:\s*\[([^\]]+)\]/g;
  let m;
  while ((m = subRe.exec(block))) {
    const sub = m[1];
    const cats = [...m[2].matchAll(/"([^"]+)"/g)].map((x) => x[1]);
    for (const cat of cats) CATEGORY_LOOKUP[cat] = { top, sub };
  }
}

function sanitize(name) {
  return name.replace(/[\\/:*?"<>|]/g, "").trim();
}

fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

let copied = 0;
const unmatched = [];
const missingPdf = [];

for (const product of products) {
  const mapping = CATEGORY_LOOKUP[product.category];
  if (!mapping) {
    unmatched.push(product);
    continue;
  }

  const srcPdf = path.join(CATALOG_DIR, `${product.slug}.pdf`);
  if (!fs.existsSync(srcPdf)) {
    missingPdf.push(product.name);
    continue;
  }

  const destDir = path.join(OUT_DIR, sanitize(mapping.top), sanitize(mapping.sub));
  fs.mkdirSync(destDir, { recursive: true });
  const destPath = path.join(destDir, `${sanitize(product.name)}.pdf`);
  fs.copyFileSync(srcPdf, destPath);
  copied++;
}

console.log(`Parsed ${products.length} products from data.ts`);
console.log(`Copied ${copied}/${products.length} catalog PDFs into ${OUT_DIR}`);
if (unmatched.length) {
  console.log(`\n${unmatched.length} product(s) with no taxonomy match:`);
  for (const u of unmatched) console.log(" -", u.name, "(category:", u.category, ")");
}
if (missingPdf.length) {
  console.log(`\n${missingPdf.length} product(s) with no catalog PDF found:`);
  for (const m of missingPdf) console.log(" -", m);
}
